import Head from "next/head";
import AppLayout from "@/common/layouts/AppLayout";
import BlogPageHeader from "@/common/modules/BlogPageHeader";
import BlogContainer from "@/common/components/containers/BlogContainer";
import Divider from "@/common/components/typography/Divider";

export default function BlogPage() {
  return (
    <>
      {/* Meta Tags */}
      <Head>
        <title>
          The Dystopian Future: How Our World Could Look in 2040 - NextSiders
          Blog
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <BlogPageHeader
          category="Future"
          title="The Dystopian Future: How Our World Could Look in 2040"
          description="The environment has been drastically changed, with the air and water becoming increasingly polluted. Animal extinctions have become commonplace, and the planet is on the brink of an ecological collapse."
          date="Feb 16, 2024"
          readTime="2 min read"
          image={{
            src: "https://images.unsplash.com/photo-1628204146743-ee4c51566096?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2832&q=80",
            height: 500,
            alt: "Blog Image",
          }}
        />

        <BlogContainer>
          <h2>What to expect from here on out</h2>
          <p>
            The year is 2040, and the world is a very different place than what
            it looks like today. We are in a dystopian future, where advances in
            technology have created an oppressive atmosphere. Climate change has
            caused rising sea levels, leading to the displacement of millions of
            people and the creation of refugee camps. Social unrest is rampant,
            and governments have become increasingly authoritarian in order to
            maintain control.
          </p>
          <blockquote>
            <p>
              People are living in a surveillance state, where their every move
              is monitored and tracked. The government has become increasingly
              oppressive, and basic human rights are being violated. The
              internet is heavily censored, and the free exchange of information
              is restricted.
            </p>
          </blockquote>
          <p>
            The economy is in shambles, with unemployment rates skyrocketing and
            wages stagnating. Wealth inequality has become so extreme that only
            a few powerful elites control the majority of the world's resources.
            The gap between the rich and the poor is growing, and the middle
            class is quickly disappearing.
          </p>
          <Divider />
          <h2>How Businesses Can Achieve Success</h2>
          <p>
            Businesses have a lot of options when it comes to achieving success.
            Here are some of the most important steps any business should take
            in order to thrive:
          </p>
          <ol>
            <li>
              <b>Make a Plan:</b> A successful business needs a strong plan.
              This plan should include a mission statement, a business model,
              and a strategy for how you will reach your goals.
            </li>
            <li>
              <b>Hire the Right People:</b> A good team is essential to any
              successful business. Hire people who are passionate about your
              mission and have the skills to help you reach your goals.
            </li>
            <li>
              <b>Build Connections:</b> Networking is key to growing a
              successful business. Make sure to build relationships with other
              businesses and customers in your industry.
            </li>
            <li>
              <b>Stay Innovative:</b> Constantly look for ways to improve your
              business and stay ahead of the competition. Try new things and be
              open to change.
            </li>
            <li>
              <b>Marketing:</b> A good marketing strategy is essential to any
              business. Make sure to reach your target audience through various
              channels and keep them engaged with your brand.
            </li>
          </ol>
          <Divider />

          <h2>What if we stack headings?</h2>
          <h3>We should make sure that looks good, too.</h3>
          <p>
            People are living in a surveillance state, where their every move is
            monitored and tracked. The government has become increasingly
            oppressive, and basic human rights are being violated. The internet
            is heavily censored, and the free exchange of information is
            restricted.
          </p>
        </BlogContainer>
      </AppLayout>
    </>
  );
}
