import Head from "next/head";
import Section from "@/common/components/containers/Section";
import AppLayout from "@/common/layouts/AppLayout";
import PageHeader from "@/common/modules/PageHeader";
import BlogGridItems from "@/common/modules/BlogGridItems";
import {
  BlogSectionContent,
  BlogSectionHeader,
} from "@/content/BlogSection.Content";

export default function BlogExcerptsPage() {
  return (
    <>
      {/* Meta Tags */}
      <Head>
        <title>NextSiders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <PageHeader center {...BlogSectionHeader} />

        <Section background="lighter">
          <BlogGridItems {...BlogSectionContent} />
        </Section>
      </AppLayout>
    </>
  );
}
