import Head from "next/head";
import Section from "@/common/components/containers/Section";
import AppLayout from "@/common/layouts/AppLayout";
import PageHeader from "@/common/modules/PageHeader";
import FeatureContent from "@/common/modules/FeatureContent";
import ImageFeatureMap from "@/assets/images/Feature.Map.png";
import {
  IconUpload,
  IconArrowAutofitDown,
  IconStars,
  IconWind,
  IconBolt,
} from "@tabler/icons";
import Hero from "@/common/modules/Hero";

export default function PricingPage() {
  return (
    <>
      {/* Meta Tags */}
      <Head>
        <title>Pricing - NextSiders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <PageHeader
          kicker="Hello"
          title="This is a custom page"
          description="This is a custom page explaining how to create a custom page."
          center
        />

        <Hero
          notfication={{
            tag: "New",
            text: "We just launched on ProductHunt!",
            button: "View Launch",
            href: "#",
          }}
          title="This is a custom page"
          description="This is a custom page explaining how to create a custom page."
          image={{ src: ImageFeatureMap, width: 250, gradientWrapper: true }}
        ></Hero>

        <Section background="lighter">
          <FeatureContent
            kicker="Instant Results"
            title="Create Your Perfect Landing Page In Seconds"
            description="Our template is perfect to create the look, act and feel of the landing page you've always wanted. With NextJs, you no longer have to compromise. Benefit from customizability, speed, security and a full suite of features."
            tags={[
              { label: "Easy Uploads", icon: <IconUpload size={17} /> },
              {
                label: "Automatic Autofit",
                icon: <IconArrowAutofitDown size={17} />,
              },
              { label: "Premium Support", icon: <IconStars size={17} /> },
              { label: "Windy Environment", icon: <IconWind size={17} /> },
              { label: "Really Fast", icon: <IconBolt size={17} /> },
            ]}
            image={{ src: ImageFeatureMap, width: 250, gradientWrapper: true }}
          />
        </Section>
      </AppLayout>
    </>
  );
}
