import Head from "next/head";
import Section from "@/common/components/containers/Section";
import AppLayout from "@/common/layouts/AppLayout";
import PageHeader from "@/common/modules/PageHeader";
import PricingTable from "@/common/modules/PricingTable";
import {
  PricingPageHeaderContent,
  PricingTableContent,
} from "@/content/PricingTable.Content";

export default function PricingPage() {
  return (
    <>
      {/* Meta Tags */}
      <Head>
        <title>Pricing - NextSiders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <PageHeader center {...PricingPageHeaderContent} />

        <Section background="lighter" className="px-4">
          <PricingTable {...PricingTableContent} />
        </Section>
      </AppLayout>
    </>
  );
}
